#!/bin/bash
javac NewMiddleware.java MiddleClient.java MiddleServer.java MiddleServerSocket.java MiddleSocketChannel.java SharedData.java MiddleWorker.java NewServerSocket.java NewWorker.java RequestHandler.java RequestWorker.java TransactionData.java
java -cp .. middleware.NewMiddleware
